export default {
  BASE_URL: process.env.REACT_APP_BASE_URL,

  // AWS config
  AWS_REGION: process.env.REACT_APP_AWS_REGION,
  AWS_ACCESS_KEY_ID: process.env.REACT_APP_AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY_ID: process.env.REACT_APP_AWS_SECRET_ACCESS_KEY_ID,
  AWS_RESOURCE_BUCKET: process.env.REACT_APP_AWS_RESOURCES_BUCKET,
  AWS_BUCKET: process.env.REACT_APP_AWS_BUCKET,
  
}
